# Generated by Django 4.2.25 on 2025-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='course',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='course_slugs_json',
            field=models.TextField(default='', verbose_name='اسلاگ دوره\u200cهای سبد خرید'),
            preserve_default=False,
        ),
    ]
