# Generated by Django 4.2.25 on 2025-11-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='مدرس هستم'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='داشجو هستم'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره همراه'),
        ),
    ]
