# Generated by Django 4.2.25 on 2025-11-03 09:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات دوره')),
                ('short_description', models.TextField(max_length=500, verbose_name='توضیحات کوتاه دوره')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت دوره (به تومان)')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان بودن دوره')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن دوره')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ دوره')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='courses/previews/', verbose_name='ویدئو پیش نمایش دوره')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='تصویر کاور دوره')),
                ('number_of_students', models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجویان')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس دوره')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درس')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوای درس')),
                ('video', models.FileField(upload_to='courses/lessons/videos/', verbose_name='ویدئو درس')),
                ('duration', models.DurationField(verbose_name='مدت زمان درس')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب درس')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='دوره')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
